version: "3.7"

# # backend api
services:
  smart:
    container_name: backend
    build: ./
    command: npm start -- -L
    working_dir: /usr/src/smart-brain-api

    environment:
      POSTGRES_URI: postgres://postgres:1234@postgres:5432/smart

    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/
    depends_on:
      - postgres

  # postgres
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: smart
      POSTGRES_PASSWORD: 1234

    env_file:
      - database.env # configure postgres

    container_name: postgres
    build: ./postgres
    ports:
      - "5432:5432"
